### ISSUE TITLE
So.. How exactly do you use this ?

### ISSUE THREAD

**Issue by Flashtheorie** [ndaba1/twinit#18]
So, i ng new an Angular application, I cd into it and then I typed
`npx twinit`

but

`npm ERR! could not determine executable to run`

So, how exactly are we supposed to use this ?

**Comment by ndaba1** [comment]
This may not be a problem with the CLI itself. Older versions of npm have had this [issue](https://github.com/npm/cli/issues/2894)
What version of node & npm are you using and on what environment??

**Comment by Flashtheorie** [comment]
Node is 16.15.1
NPM is 8.19.2

**Comment by ndaba1** [comment]
Then perhaps npx might be using a cached older version that was problematic. 
You might try running :
`npx twinit@latest` to make sure that npx is using the latest version

**Comment by Flashtheorie** [comment]
It solved the problem indeed, thank you ! 

PS : I must say this is a simple, yet amazing thing !

**Comment by ndaba1** [comment]
Thanks.
The npm cache should be updated soon and you won't need to hardcode the `@latest`.
